Adding parallel training functionality to the Experiment and Model
vc1492a/tidd pull request #97
Opened 2021-06-25 06:40 UTC by hamlinliu17

Resolving the issue (here)[https://github.com/vc1492a/tidd/issues/84] finally. We can now specify the cuda devices specifically the indices on cuda devices.

2021-06-25 16:29 UTC, vc1492a requested changes
@hamlinliu17 please clean up the merge artifacts and then commit the changes. Once you see that the tests pass in [Travis CI](https://travis-ci.com/github/vc1492a/tidd/branches), please go ahead and merge into the `dev` branch. 

Following that, please do the following: 

- Increment the version number and update the version number throughout the code (`setup.py`, `readme.md`, etc.). 
- Update `changelog.md` to reflect the new version number and describe the changes made. 
- Create a distribution in `dist` directory once you have run the tests and verified that the code works as intended. 
- Commit these changes to the `dev` branch and then ping me to review. We'll then pull the changes into the `main` branch. Thanks!

2021-06-25 16:29 UTC, vc1492a commented on tidd/modeling.py
> +<<<<<<< HEAD
Please remove the inserts in the file from a merge.

2021-06-25 16:29 UTC, vc1492a commented on tidd/modeling.py
> +=======
Another one

2021-06-25 16:29 UTC, vc1492a commented on tidd/modeling.py
> +>>>>>>> dev
one more

2021-06-27 18:13 UTC, hamlinliu17 commented
@vc1492a I am going to merge this but the coverage of the tests has been lowered now.

2021-06-27 18:14 UTC, merged